### ISSUE TITLE
Unfinished Checklist

### ISSUE THREAD

**Issue by bhurivaj** [bhurivaj/cm#1]
General
- [x] ปรับใช้ validate.js แทนของ framework
  - [x] Partner
  - [x] Product
  - [x] Inventory
  - [x] Inventory_wh
  - [x] All HR
- [x] เปลี่ยน format date ใน mysql, บันทึกค่าใหม่ และ เปลี่ยนวิธีการแปลงค่าก่อนบันทึก และหลังจากดึงจาก db
  - [x] hr_att
  - [x] hr_employee_data
  - [x] hr_holiday
  - [x] hr_leave
  - [x] inventory_move
  - [x] inventory_move_tr
  - [x] product
  - [x] rental
  - [x] rentaltransaction
- [x] เปลี่ยนการแสดงผลตำบล อำเภอ จังหวัดให้เป็นแบบ json เพื่อการง่าย

---

Login
- [x] ทำระบบ Login/Logout
- [x] ทำระบบลืม password
- [x] ทำระบบ สร้าง/แก้ไข user
- [x] ทำระบบจำกัดสิทธิ์
- [x] ทำระบบจัดกลุ่ม

Inventory
- [x] ตรวจสอบว่า มันมีรายการซ้ำกันหรือไม่ ถ้ามีให้แจ้งเตือนก่อน add
- [x] ทำการบันทึกว่ารายการแก้ไขปรับปรุงเมื่อไร
- [x] สร้างฟอร์ม ใบรับ/เบิกสินค้า
- [x] สร้างรายงานแสดงรายการสินค้าคงเหลือ
- [x] ตั้งตัดรายงานแสดงรายการสินค้าคงเหลือ ตามวันที่
- [x] เปลี่ยนอิงรายชื่อลูกค้าเป็นแบบ autocomplete เข้ากับรายชื่อ/code ลูกค้า  และรหัส/รายชื่อโครงการ

HR
- [x] ทำระบบการคำนวณวันทำงานและวันหยุด
- [x] ทำระบบวันหยุดประจำปี
- [x] ทำระบบตรวจสอบการมาทำงาน การขาด การลา
- [x] แสดงการลาเป็นรูปแบบปฏิทิน

Partner
- [x] สร้าง Code แยกตามประเภท Partner และกลุ่มธุรกิจ
- [x] แก้ไข จังหวัด อำเภอ ตำบล
